name: remote ssh command
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Use curl
        uses: sozo-design/curl@v1.0.2
      - run: curl icanhazip.com
        id: get-ip
      - name: Get public IP
        run: | 
          my_public_ip=$(curl -s icanhazip.com)
          echo "HOST=$my_public_ip" >> $GITHUB_ENV
          echo "USERNAME=admin" >> $GITHUB_ENV
          echo "PASSWORD='$my_public_ip'" >> $GITHUB_ENV
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ env.HOST }}
          username: ${{ env.USERNAME }}
          password: ${{ env.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: whoami
 
