name: UBUNTU_SERVER
on:
  push:
    branches:
      - main  
jobs:
  my-job:
    runs-on: ubuntu-latest
    container:
      image: aschmelyun/cleaver:latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run a command inside the container
        run: echo "Hello from the Docker container!"
