name: Deployment

on:
  push:
    branches:
    - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Use curl
      uses: sozo-design/curl@v1.0.2     
    - run: curl icanhazip.com
    - name: Get public IP
      run: |
        my_public_ip=$(curl -s icanhazip.com)
        echo "My public IP address is: $my_public_ip"
    - uses: LuisEnMarroquin/setup-ssh-action@v2.0.0
      with:
        ORIGIN: $my_public_ip # example.com || 8.8.8.8
        SSHKEY: ${{ secrets.SSH }} # ----- BEGIN RSA PRIVATE KEY----- ...
        NAME: production
        PORT: 22 # 3000
        USER: admin # admin
    - run: ssh production ls --help
